### ISSUE TITLE
Fix incorrect amount displayed in migration summary

### ISSUE THREAD

**Issue by evavirseda** [iotaledger/iota#4562] opened 2024-12-19 09:22 UTC
There seems to be a discrepancy between the IOTA amount displayed in the migration summary and the actual amount signed in the transaction.

![Image](https://github.com/user-attachments/assets/0a1327b4-c3eb-4cc7-843c-031605b5303c)

For example, in the summary, it shows that 38 IOTA will be migrated. However, when the transaction is signed, the total received is 61.19 IOTA.

The IOTA amount shown in the summary should match the actual IOTA amount signed in the transaction.

[context](https://github.com/iotaledger/iota/pull/4547#discussion_r1890276874)

**Comment by brancoder** [comment] 2024-12-19 18:55
looks like the amounts are correct because there are Iota coins in every object, also from provided screenshot its not visible if there are some other grouped IOTA coins in the list similar to this >
![Image](https://github.com/user-attachments/assets/008b88f3-b89c-427f-8426-25d7d6a8f85a)

⏫  in this example there are 12 iota coins which is actually 12 objects with 1 iota and same timestampe and that is why they are grouped in the same object on the list. but down on the list there is again 6 IOTA.
Also total amount of migratable Iotas is 27 which is stated in the initial Card.

If user clicks migrate than the amount in the approval request is also 27 which corresponds to the migratable amount in the dashboard>
![Image](https://github.com/user-attachments/assets/50857ea8-5674-4ab2-8358-095dec8a91ad)

@evavirseda  & @cpl121 Could we please retest this and provide some more details if the issue is really there? 🙏

**Comment by brancoder** [comment] 2024-12-20 11:49
After investigating the issue the problem is not with the incorrect amount but rather with the UX of the migration flow. The amounts in the transactions need to be displayed in a more user friendly way thats why this task will be closed in favor of these UX tasks:
https://github.com/iotaledger/iota/issues/4577
https://github.com/iotaledger/iota/issues/4624

**Closed as not planned** 2024-12-20 11:49 UTC
Labels: tooling, wallet-dashboard
